### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED on some sites / certify cacert.pem / get_default_verify_paths

### ISSUE THREAD

**Issue by x00** [gwik/geventhttpclient#84] opened 2017-03-28 11:06 UTC
Ubuntu a directory not a file for CAs, so you use `certifi.where()` in your connectionpool.py code

Can't figure thsi out. All I know is that requests uses a pretty similar if not identical cacert.pem and is having no issues.

if I do

```python
ua =  UserAgent()
ua.urlopen('https://bison.streethawk.com/v1/installs/push_history');
```

I get `ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

ali I can do is disable verification for now.

Like I say I can use requests with no issues, but that is not fit for purpose.

**Comment by x00** [comment] 2017-03-28 11:10
btw this changed when ssl was updated

`OpenSSL 1.0.2g  1 Mar 2016`

**Comment by x00** [comment] 2017-03-28 12:52
I'm having issues disabling this.

**Comment by x00** [comment] 2017-03-28 13:06
I'm using `CERT_NONE` in connectionpool.py and also commented out the line

```
    #if not cert:
    #    raise ValueError("empty or no certificate, match_hostname needs a "
    #                     "SSL socket or SSL context with either "
    #                     "CERT_OPTIONAL or CERT_REQUIRED")
```
in backports/ssl_match_hostname/__init__.py    and urllib3/packages/ssl_match_hostname/_implementation.py

but I'm getting that very same error. I can't find where that code is located. 

I don't want to disable this but I need to test ASAP.

**Comment by x00** [comment] 2017-03-28 13:29
how can I override "empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED" error?

**Comment by x00** [comment] 2017-03-28 17:05
ok I have a temporary workaround (not recommended for production). This is applicable to ubuntu.

in  `/usr/lib/python2.7/ssl.py` after `def match_hostname(cert, hostname):` put `return`
in `/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py` replace `'cert_reqs': gevent.ssl.CERT_REQUIRED` with `'cert_reqs': gevent.ssl.CERT_NONE`

**Comment by laurentL** [comment] 2020-03-31 12:28
Duplicate of #124

**Closed** 2020-05-22 12:08 UTC
